export const fullTinyMceConfig = {
    menubar: false,
    branding: false,
    toolbar:
        'styles | myimagebutton | bullist numlist | formatselect | bold italic backcolor | alignleft aligncenter alignright alignjustify | outdent indent | removeformat undo redo | fullscreen | code',
    plugins: [
        'advlist',
        'autolink',
        'lists',
        'link',
        'image',
        'charmap',
        'anchor',
        'searchreplace',
        'visualblocks',
        'code',
        'fullscreen',
        'insertdatetime',
        'media',
        'table',
        'preview',
        'help',
        'wordcount',
    ],
    content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
    block_formats: 'Paragraph=p; Heading 1=h1; Heading 2=h2; Heading 3=h3; Heading 4=h4; Heading 5=h5',
    style_formats: [
        { title: 'Heading 1', block: 'h1' },
        { title: 'Heading 2', block: 'h2' },
        { title: 'Heading 3', block: 'h3' },
        { title: 'Heading 4', block: 'h4' },
        { title: 'Heading 5', block: 'h5' },
        { title: 'Paragraph', block: 'p' },
    ],
}